export const adventureTimeCharacters = [
	'Finn The Human',
	'Jake The Dog',
	'Princess Bubblegum',
	'Marceline the Vampire Queen',
	'BMO',
	'Lumpy Space Princess',
	'Ice King',
	'Peppermint Butler',
	'Gunter',
	'The Lich',
	'Lady Rainicorn',
	'Flame Princess',
	'Muscle Princess',
	'Tree Trunks',
	'Cinnamon Bun',
	'Desert Princess',
	'Lemongrab',
	'Hot Dog Princess',
	'Wildberry Princess',
	'Snail',
	'Adventure Tim',
	'Flame King',
	'Starchy',
	'Neptr',
	'Princess Chewypaste',
	'Raggedy Princess',
	'Breakfast Princess',
	'Slime Princess',
	'Ghost Princess',
	'Hunson Abadeer'
];
